[package]
name = "sound"
version = "0.1.0"
edition = "2021"
description = "Ultra-minimal Piano Keyboard Sound Simulator - Maps keyboard keys to musical notes in real-time"
authors = ["Your Name <your.email@example.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/yourusername/piano-keyboard-sound-simulator"
keywords = ["audio", "piano", "keyboard", "music", "minimal"]
categories = ["multimedia::audio"]

[dependencies]
cpal = "0.15"
device_query = "2.0"
