#!/bin/bash

# CodeBeats Demo - Simple Musical Programming Experience

echo "🎼 CodeBeats - Musical Programming Demo 🎼"
echo "=========================================="
echo ""
echo "Experience programming languages as unique musical scales!"
echo ""

echo "🎵 Available Language Scales:"
echo ""
echo "🦀 RUST - C Minor Pentatonic (Powerful, direct)"
echo "   Notes: C - Eb - F - G - Bb"
echo "   Try: cargo run config language_configs/rust.json"
echo ""
echo "🌐 JAVASCRIPT - D Mixolydian (Modern, jazzy)"
echo "   Notes: D - E - F# - G - A - B - C"
echo "   Try: cargo run config language_configs/javascript.json"
echo ""
echo "⚙️  C - A Natural Minor (Serious, precise)"
echo "   Notes: A - B - C - D - E - F - G"
echo "   Try: cargo run config language_configs/c.json"
echo ""
echo "🐹 GO - G Major Pentatonic (Clean, simple)"
echo "   Notes: G - A - B - D - E"
echo "   Try: cargo run config language_configs/go.json"
echo ""
echo "🐍 PYTHON - F Major (Warm, friendly)"
echo "   Notes: F - G - A - Bb - C - D - E"
echo "   Try: cargo run config language_configs/python.json"
echo ""

echo "🔍 Analysis and Comparison:"
echo "   cargo run compare-scales     # Detailed musical analysis"
echo ""

echo "🎮 Quick Test:"
echo "   1. Pick a language: cargo run config language_configs/<language>.json"
echo "   2. Start typing code in that language"
echo "   3. Notice the unique musical character!"
echo "   4. Press Ctrl+C to stop"
echo ""

echo "💡 Key Features:"
echo "   • Each language uses a different musical scale"
echo "   • Scales match programming language philosophy"
echo "   • Comfortable frequency range (65-1047 Hz)"
echo "   • No ear fatigue during extended coding"
echo ""

echo "🎹 Ready to experience musical programming!"
echo "Pick a command above and start coding! ✨"
